# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-31 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190330_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='points',
            field=models.CharField(max_length=150, verbose_name='教学特点'),
        ),
    ]
