# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-31 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20190331_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='teacher/default/timg.jpg', null=True, upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
