# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190402_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='click_nums',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='后端开发', max_length=20, verbose_name='课程类别'),
        ),
    ]
