# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190403_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='shabi',
            field=models.CharField(default='', max_length=20, verbose_name='傻逼'),
        ),
    ]
