# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='need_know',
            field=models.CharField(default='', max_length=100, verbose_name='课程描述'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_all',
            field=models.CharField(default='', max_length=100, verbose_name='课程须知'),
        ),
    ]
