# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20190404_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='need_know',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='课程须知'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_all',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='老师告诉你'),
        ),
    ]
