# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190326_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='media/user_image/default.png', upload_to='media/user_image/%Y/%m'),
        ),
    ]
