# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190401_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='user_image/default.png', null=True, upload_to='user_image/%Y/%m'),
        ),
    ]
